qld-gov-au/ckanext-xloader

- ckanext/xloader/jobs.py
- ckanext/xloader/plugin.py
Concatenating a string and a timestamp requires `format`, not just `+`.
> QOL-9327 fix syntax for new query string parameter

- ckanext/xloader/helpers.py
- ckanext/xloader/tests/test_loader.py
- Our test IDs don't have the right format, and we should avoid hardcoding IDs anyway
> [QOLDEV-424] fix tests to avoid hardcoding resource IDs

- ckanext/xloader/tests/test_loader.py
- This is intermittently breaking the boston_311 test, when columns load in an unexpected order
> [QOLDEV-424] ensure consistent column name ordering in tests

- ckanext/xloader/action.py
- ckanext/xloader/jobs.py
- ckanext/xloader/loader.py
- ckanext/xloader/utils.py
- Tabulator is good at type guessing but is slow. Once it has configured the column types, there's no need to use it every time.
> [QOLDEV-490] use fast loading for resources that already have a data dictionary

- ckanext/xloader/config_declaration.yaml
- ckanext/xloader/jobs.py
- ckanext/xloader/templates/package/resource_read.html
- ckanext/xloader/utils.py
- Ignore the 'use_type_guessing' flag for large files since they will take too long.
> [QOLDEV-490] always use COPY for large files

- ckanext/xloader/action.py
- ckanext/xloader/jobs.py
- Can't multiply a string by 3, we get repeated text instead of arithmetic multiplication
> [QOLDEV-490] fix timeout extension

- ckanext/xloader/loader.py
Windows-1252 is a superset, so it's better for examining an unknown file
> QOLSVC-2984 Sniff with Windows-1252 encoding rather than Latin-1

- ckanext/xloader/templates/xloader/resource_data.html
https://github.com/qld-gov-au/ckanext-xloader/pull/68 is a useful feature but the layout is wrong.
- Add a space between the label icon and text
- Float the button right so it coexists properly with the Upload button
> fix datastore delete button layout from #68

- ckanext/xloader/templates/xloader/resource_data.html
- Move variable definitions inside the relevant blocks as they don't seem to be effective otherwise. This would have resulted in the delete button submitting to the current URL, which refreshes the data, instead of deleting, if the confirm-action JavaScript runs.
> Fix datastore deletion button

- ckanext/xloader/loader.py
- ckanext/xloader/plugin.py
- ckanext/xloader/tests/test_loader.py
- Use TRUNCATE when fields are unchanged, instead of dropping and recreating the table
- Preserve sniffed types unless manually overridden
> QOLSVC-3902 adjust loading behaviour to reduce deadlocks

- ckanext/xloader/loader.py
- When clearing and reloading a resource, shorten the lock timeout so we fail fast instead of deadlocking
> [QOLSVC-3902] reduce lock timeout to avoid deadlocks

- ckanext/xloader/db.py
- ckanext/xloader/jobs.py
- ckanext/xloader/utils.py
When jobs fail to acquire locks, or encounter deadlocks, return them to the back of the queue instead of dropping them.
> [QOLSVC-3902] retry jobs that fail to acquire locks

- README.rst
- This affects the behaviour of COPY, so it is very relevant to XLoader
> [QOLDEV-708] document the PostgreSQL datestyle setting

- ckanext/xloader/action.py
- ckanext/xloader/auth.py
- ckanext/xloader/cli.py
- ckanext/xloader/command.py
- ckanext/xloader/jobs.py
- ckanext/xloader/tests/test_action.py
- ckanext/xloader/tests/test_loader.py
- ckanext/xloader/utils.py
- This will allow eg support staff processing a critical resource immediately while a large job is occupying the queue
> [QOLSVC-4689] add CLI option to process datasets immediately, #202

- ckanext/xloader/jobs.py
- Type guessing could fail eg if the first hundred rows are a consistent type but it changes later. Mirror the existing fallback behaviour by trying both styles, but in an order determined by the type guessing flag.
> [QOLSVC-4959] try direct COPY if type guessing fails

- ckanext/xloader/helpers.py
- ckanext/xloader/loader.py
- Excel tends to generate files with lots of extra commas at the end of every row. The header row ignores them, so data rows need to be able to ignore them as well.
- Also strip trailing whitespace from headers after truncating them, in case the truncation exposed some, see https://github.com/ckan/ckanext-xloader/pull/210/
> [QOLSVC-5123] handle empty cells past end of row

- ckanext/xloader/loader.py
Some publishers are relying on generated IDs to be stable.
> [QOLSVC-5551] restart all sequences when truncating table

- ckanext/xloader/templates/package/resource_read.html
- ckanext/xloader/templates/package/snippets/resource_info.html
- ckanext/xloader/templates/package/snippets/resource_item.html
- ckanext/xloader/webassets/css/xloader.css
not on the outer that is not rendered
> fix: asset inclusion must be in the block being rendered,

- ckanext/xloader/helpers.py
- ckanext/xloader/plugin.py
- ckanext/xloader/tests/test_loader.py
- ckanext/xloader/tests/test_plugin.py
- ckanext/xloader/utils.py
- Recognise the four-letter string 'None' (not just literal None) as an acceptable value for 'url_type'
> [QOLSVC-8504] fix missing DataStore button on resource after lock timeout

- ckanext/xloader/jobs.py
- ckanext/xloader/tests/test_action.py
- ckanext/xloader/tests/test_jobs.py
Built-in `hash` is inconsistent across Python executions, for cryptographic reasons, which is the opposite of what we want. Replaced with a very simple check of the first character in the package ID.
> QOLSVC-4633 improve hash method and add more tests
